import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./ui/components/Navbar";
import { ToastContainer } from "react-toastify";
import Footer from "./ui/components/Footer";
import CmsContextProvider from "./context/CmsContext";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CmsContextProvider>
          <ToastContainer autoClose={2000} position="top-center" />
          <Navbar />
            <div className=" px-10 md:px-[10%]">{children}</div>
          <Footer />
        </CmsContextProvider>
      </body>
    </html>
  );
}
